### ISSUE TITLE
Remove supported for Symfony 2.3

### ISSUE THREAD

**Issue by stloyd** [SymfonyTest/SymfonyDependencyInjectionTest#74]
We should drop support for Symfony `< 2.7` cause those versions are not maintained anymore.

**Comment by matthiasnoback** [comment]
Responding to your question about a 3.0 release, I don't think this issue would force us to do that. Dropping support for older versions simply means that people won't automatically upgrade to new minor versions anymore, it doesn't mean a BC break for them. Right?

**Comment by VasekPurchart** [comment]
@matthiasnoback I think what you are saying about not breaking for older version is correct, but from my experience it is still better to create new major version, because then it gives you "space" to create more releases based on the older major version, should the need arise (fixing a critical bug etc.).

**Comment by stof** [comment]
fixing a critical bug happens in a patch release, which is possible even if dropping support was done in a minor version.
What using a minor version forbids you is to add new features in the older branch (as this would require a minor version release)

**Comment by matthiasnoback** [comment]
Right, you can always release new patch versions (you can always branch off of an existing minor version tag). So, if you like, just go ahead with requiring higher versions of Symfony for the next minor release.

**Comment by Nyholm** [comment]
This is done in master
