### ISSUE TITLE
1.2.0 is not BC with 1.1.*

### ISSUE THREAD

**Issue by reyostallenberg** [SymfonyTest/SymfonyDependencyInjectionTest#97]
The 3 lines changed here https://github.com/SymfonyTest/SymfonyDependencyInjectionTest/pull/87/files#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R18 are not changed BC.

It should be `^2.7 || ^3.0 || ^4.0`.

This is why I have problems now upgrading a library that need to support sf4.0 and sf3.2.

Can I make a PR to fix this issue?

**Comment by Nyholm** [comment]
Thank you for this issue. I have some thoughts:
- Support for Symfony 3.2 [ended last month](https://symfony.com/roadmap?version=3.2#checker). 
- Updating an application from 3.1 to 3.2 is a [super simple thing](https://github.com/symfony/symfony/blob/3.4/UPGRADE-3.3.md) to do. 

Is there any specific reason you want to support sf 3.2?

**Comment by reyostallenberg** [comment]
You're right. No specific reason. I'll upgrade the libraries requirement.
(but it's not really semver bc, this changes).
Thanks for thinking with me.

**Comment by xabbuh** [comment]
From my point of view, there is no BC breaks here. If you were stuck at Symfony 3.0 to 3.2, you would just not get any updates because Composer prevents them from being installed. This is more or less the same as a library not being supported anymore. I would only consider such a change as a BC break if only the code were changed to assume that Symfony 3.3 were installed because in that case you would be able to pull in the new release we would then break because of code not being present.
